version: 1.0.{build}
image: Visual Studio 2019

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:

- cmd: >-
    dotnet restore 
    dotnet build  -c Release
    dotnet pack .\src\RekhtaDownloader\RekhtaDownloader.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: '**\*.nupkg'
  name: NugetPackage

deploy:
- provider: NuGet
  api_key:
    secure: QHBYaFSHQOYnBY6XwHIsGyEtgntE4/PUCKrPq3dx0Kt91v41LNvBBrsKHzLHHuP4
  artifact: /.*\.nupkg/