name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Build
        run: dotnet build ./src/RekhtaDownloader/RekhtaDownloader.csproj --configuration Release -p:Version=1.1.${{ github.run_number }}

      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

      - name: Publish win-x64 App
        run: dotnet publish ./src/RekhtaDownloader.Console/RekhtaDownloader.Console.csproj -r win-x64 -c Release --self-contained

      - name: Zip  win-x64 artifacts
        working-directory: ./src/RekhtaDownloader.Console/bin/Release/net8.0/win-x64/publish
        run: zip -qq -r release-win-x64-1.1.${{ github.run_number }}.zip .

      - name: Publish win-x86 App
        run: dotnet publish ./src/RekhtaDownloader.Console/RekhtaDownloader.Console.csproj -r win-x86 -c Release --self-contained

      - name: Zip  win-x86 artifacts
        working-directory: ./src/RekhtaDownloader.Console/bin/Release/net8.0/win-x86/publish
        run: zip -qq -r release-win-x86-1.1.${{ github.run_number }}.zip .

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 1.1.${{ github.run_number }}
          tag_name: 1.1.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload windows x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/RekhtaDownloader.Console/bin/Release/net8.0/win-x64/publish/release-win-x64-1.1.${{ github.run_number }}.zip
          asset_name: release-win-x64-1.1.${{ github.run_number }}.zip
          asset_content_type: application/zip

      - name: Upload windows x86 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/RekhtaDownloader.Console/bin/Release/net8.0/win-x86/publish/release-win-x86-1.1.${{ github.run_number }}.zip
          asset_name: release-win-x86-1.1.${{ github.run_number }}.zip
          asset_content_type: application/zip
